/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pakage1;

/**
 *
 * @author HP
 */
public class newTable extends javax.swing.JFrame {

    /**
     * Creates new form newTable
     */
    public newTable() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        gender = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        middle = new javax.swing.JTextField();
        status = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(183, 30, 30));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 880, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("DOCTOR");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 60, 120, 30);

        jLabel2.setText("Email:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(480, 450, 60, 30);

        jLabel3.setText("ID:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 330, 120, 30);

        jLabel4.setText("Lastname:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 370, 120, 30);

        jLabel5.setText("Firstname:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 410, 120, 30);

        jLabel6.setText("Middle:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 450, 120, 30);

        jLabel7.setText("Gender:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 490, 120, 30);

        jLabel8.setText("Status:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(480, 330, 60, 30);

        jLabel9.setText("Address:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(480, 370, 60, 30);

        jLabel10.setText("Contact:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(480, 410, 60, 30);
        jPanel1.add(gender);
        gender.setBounds(170, 490, 260, 30);
        jPanel1.add(id);
        id.setBounds(170, 330, 260, 30);
        jPanel1.add(lname);
        lname.setBounds(170, 370, 260, 30);
        jPanel1.add(fname);
        fname.setBounds(170, 410, 260, 30);
        jPanel1.add(middle);
        middle.setBounds(170, 450, 260, 30);
        jPanel1.add(status);
        status.setBounds(540, 330, 260, 30);
        jPanel1.add(address);
        address.setBounds(540, 370, 260, 30);
        jPanel1.add(contact);
        contact.setBounds(540, 410, 260, 30);
        jPanel1.add(email);
        email.setBounds(540, 450, 260, 30);

        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(12, 100, 860, 170);

        jButton1.setForeground(new java.awt.Color(255, 51, 51));
        jButton1.setText("DISPLAY");
        jPanel1.add(jButton1);
        jButton1.setBounds(510, 280, 110, 30);

        jButton2.setForeground(new java.awt.Color(255, 51, 51));
        jButton2.setText("ADD");
        jPanel1.add(jButton2);
        jButton2.setBounds(30, 280, 110, 30);

        jButton3.setForeground(new java.awt.Color(255, 51, 51));
        jButton3.setText("UPDATE");
        jPanel1.add(jButton3);
        jButton3.setBounds(150, 280, 110, 30);

        delete.setForeground(new java.awt.Color(255, 51, 51));
        delete.setText("DELETE");
        jPanel1.add(delete);
        delete.setBounds(270, 280, 110, 30);

        clear.setForeground(new java.awt.Color(255, 51, 51));
        clear.setText("CLEAR");
        jPanel1.add(clear);
        clear.setBounds(390, 280, 110, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JButton clear;
    private javax.swing.JTextField contact;
    private javax.swing.JButton delete;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fname;
    private javax.swing.JTextField gender;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField middle;
    private javax.swing.JTextField status;
    // End of variables declaration//GEN-END:variables
}
